### ISSUE TITLE
Unsolicited Life Jolt

### ISSUE THREAD

**Issue by LiGoldragon** [EPonyA/Superstar-Game-Suite#13]
Hey Kid, I like your auric field. I was into virtual games a lot as a kid too. Recently, I discovered Eric Dubay's videos, watched Dave Murphy debate the best physicists that want to debate, and it changed everything. Check it out. Don't laugh at it untli you've seriously considered what they propose. Long story short: Read Carlos Castaneda. Virtual games are energy body killers. Ask me anything.

Much love
~ Li Goldragon

**Comment by Cons-Cat** [comment]
Hi!

I don't think I have worked on this project since I was 20. Despite my bachelor's degree in game development, I actually haven't played video games in years. I don't see much point, since they're usually non-libre, and almost always hold less artistic merit than clopfic, although I have mastered speedrunning a route in Trials in Tainted Space where you can interrogate two imprisoned bumblebee studs who then pin your arms and spit roast you (you can optionally consent, but I prefer to resist), meanwhile an anthro fox cop masturbates behind the safety of her jail bars. I have also speed-ran [Toadette Strikes](https://mfgg.net/index.php?act=resdb&param=02&c=2&id=30718) in the past.

Anyways, I'm not much of a gamer, and honestly even when I did play League of Legends 10 hours per day most days of the week like any self respecting gamer would, I was only into it because of Kindred yiff. Every single LoL match made me angry beyond belief, so I would wind down by ejaculating during the ridiculously long match-up queue times. I could have gotten into games faster if I played support, but I do not find support champions attractive. Besides, the post nut clarity achieved me tactical perfection. I knew precisely when to rotate bot lane for a counter-gank right before their red buff respawns for my taking. Those nofap bronze leaguers _never_ saw me coming.

But these days I hold much more intellectual hobbies, like reading the insane political psycho thriller clopfics by Concordion, or browsing the latest TF/TG and Lucario uploads to e621. Have you ever met [Spike](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi.pinimg.com%2Foriginals%2Faa%2Fc9%2F3b%2Faac93b5288ad333c70c7eb1a648bf94c.png&f=1&nofb=1&ipt=016ac23494f7df5c3824836d559b2490ffe4ea0441bb87e67572fb344a6ff66f&ipo=images)? I'm kind of in love with him. Due to being written in untyped Javascript, it is difficult to query how many Spike clopfics I've read on [fimfiction.net](https://www.fimfiction.net/user/274199/Conscat/library), but I'm sure it's a lot.

After Rust becomes the only programming language used for anything and I'm put out of C++ work forever, I plan on moving to Thailand and living out the rest of my days writing my own insane political psycho thriller clopfics about Spike and his LGBTQ harem.

Oh yeah, I might restart this software in a few years, but it will be done so using [libCat](https://github.com/Cons-Cat/LibCat) because nobody other than me knows how to make software. Thanks for the video rec's, I'll let you know when I've watched them!

Much love
~ Conscat

**Comment by LiGoldragon** [comment]
Nice to get a friendly response. Check out archaix.com. Good luck! :pray:
